# Generated by Django 4.2.1 on 2023-05-18 16:21

from django.db import migrations, models
import wagtail.fields
import wagtailiconchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stream_field_with_icon',
            field=wagtail.fields.StreamField([('icon', wagtailiconchooser.blocks.IconChooserBlock())], blank=True, null=True, use_json_field=True),
        ),
    ]
