# Generated by Django 4.2.1 on 2026-06-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_icon_homepage_stream_field_with_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='icon_allowed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
